version: 2
updates:
   - package-ecosystem: github-actions
     directory: /
     schedule:
        interval: weekly
     assignees:
        - "hannesbraun"
     reviewers:
        - "hannesbraun"
     target-branch: "dev"
   - package-ecosystem: maven
     directory: /
     schedule:
        interval: weekly
     assignees:
        - "hannesbraun"
     reviewers:
        - "hannesbraun"
     target-branch: "dev"
